[build]
publish = "site/public"
command = "cd site && hugo --themesDir ../.."

[build.environment]
HUGO_VERSION = "0.78.2"
HUGO_THEME = "repo"
HUGO_BASEURL = "https://haicheviet.com"

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"