# Text Colors: (Title, @, Subtitle, Colon, Value, Extra)
# 2 is Green, 7 is White
colors=(2 2 7 2 7 7)

# ASCII Colors:
# This will turn the Venusaur art Green
ascii_colors=(2)

print_info () {
    prin
    prin "$(color 5)haiche@venusaur"
    prin
    prin "$(color 2)Host" "Personal Blog"
    prin "$(color 2)Title" "LLM Engineering Manager"
    prin "$(color 2)Company" "VinSmart Future"
    info "Theme" theme
    info "Icons" icons
    prin "$(color 2)Terminal" "zsh" 
    prin "$(color 2)Font" "Source Code Pro"
    prin "$(color 2)Format" "GIF"

    info cols
}

image_source="$(cat /home/haiche/Documents/personal-space/scripts/introduction-gif/pokemon.txt)" # Remember to change this path
gap=-1